-- Generated by scripts/generate_cloudflare_schema.py
CREATE TABLE IF NOT EXISTS "users" (
  "id" INTEGER PRIMARY KEY,
  "username" TEXT NOT NULL UNIQUE,
  "hashed_password" TEXT NOT NULL,
  "role" TEXT NOT NULL,
  "display_name" TEXT,
  "is_active" INTEGER,
  "created_at" TEXT
);

CREATE TABLE IF NOT EXISTS "claimers" (
  "id" INTEGER PRIMARY KEY,
  "name" TEXT NOT NULL UNIQUE,
  "role" TEXT,
  "email" TEXT,
  "phone" TEXT,
  "color" TEXT,
  "default_room" TEXT,
  "notes" TEXT,
  "created_at" TEXT
);

CREATE TABLE IF NOT EXISTS "rooms" (
  "id" INTEGER PRIMARY KEY,
  "name" TEXT NOT NULL UNIQUE,
  "description" TEXT,
  "category" TEXT,
  "created_at" TEXT
);

CREATE TABLE IF NOT EXISTS "cages" (
  "id" INTEGER PRIMARY KEY,
  "cage_code" TEXT NOT NULL,
  "room" TEXT,
  "strain" TEXT,
  "gender" TEXT,
  "cage_type" TEXT,
  "capacity" INTEGER,
  "mating_date" TEXT,
  "observation" TEXT,
  "notes" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

CREATE TABLE IF NOT EXISTS "mouse_statuses" (
  "id" INTEGER PRIMARY KEY,
  "name" TEXT NOT NULL UNIQUE,
  "is_system" INTEGER NOT NULL,
  "removes_from_cage" INTEGER NOT NULL,
  "sort_order" INTEGER NOT NULL,
  "created_at" TEXT,
  "updated_at" TEXT
);

CREATE TABLE IF NOT EXISTS "mice" (
  "id" INTEGER PRIMARY KEY,
  "mouse_code" TEXT NOT NULL UNIQUE,
  "cage_id" INTEGER REFERENCES "cages"("id") ON DELETE SET NULL,
  "strain" TEXT,
  "gender" TEXT,
  "dob" TEXT,
  "parents" TEXT,
  "genotype_1" TEXT,
  "genotype_2" TEXT,
  "test_date" TEXT,
  "owner_id" INTEGER REFERENCES "claimers"("id") ON DELETE SET NULL,
  "owner_name" TEXT,
  "status" TEXT,
  "claim_date" TEXT,
  "claim_purpose" TEXT,
  "source_room" TEXT,
  "notes" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

CREATE TABLE IF NOT EXISTS "genotype_records" (
  "id" INTEGER PRIMARY KEY,
  "mouse_code" TEXT NOT NULL,
  "mouse_id" INTEGER REFERENCES "mice"("id") ON DELETE CASCADE,
  "test_date" TEXT,
  "strain" TEXT,
  "dob" TEXT,
  "gender" TEXT,
  "parents" TEXT,
  "genotype_1" TEXT,
  "genotype_2" TEXT,
  "genotype_3" TEXT,
  "op_record" TEXT,
  "notes" TEXT,
  "created_at" TEXT
);

CREATE TABLE IF NOT EXISTS "transfer_requests" (
  "id" INTEGER PRIMARY KEY,
  "seq" TEXT,
  "request_date" TEXT NOT NULL,
  "demander" TEXT NOT NULL,
  "strain" TEXT NOT NULL,
  "age_gender_req" TEXT,
  "target_room" TEXT,
  "cage_count" INTEGER,
  "source_room" TEXT,
  "mouse_gender" TEXT,
  "mouse_codes" TEXT,
  "status" TEXT,
  "feedback" TEXT,
  "handler" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

CREATE TABLE IF NOT EXISTS "transfer_request_assignments" (
  "id" INTEGER PRIMARY KEY,
  "request_id" INTEGER NOT NULL REFERENCES "transfer_requests"("id") ON DELETE CASCADE,
  "mouse_id" INTEGER NOT NULL UNIQUE REFERENCES "mice"("id") ON DELETE CASCADE,
  "original_state" TEXT NOT NULL,
  "assigned_state" TEXT NOT NULL,
  "source_room" TEXT,
  "source_cage" TEXT
);

CREATE TABLE IF NOT EXISTS "transfer_logs" (
  "id" INTEGER PRIMARY KEY,
  "action_type" TEXT,
  "mouse_codes" TEXT NOT NULL,
  "mouse_count" INTEGER,
  "claimer_name" TEXT,
  "source_room" TEXT,
  "target_room" TEXT,
  "source_cage" TEXT,
  "target_cage" TEXT,
  "operator" TEXT,
  "date" TEXT,
  "status" TEXT,
  "notes" TEXT,
  "created_at" TEXT
);

CREATE TABLE IF NOT EXISTS "primers" (
  "id" INTEGER PRIMARY KEY,
  "primer_no" INTEGER,
  "strain_short" TEXT,
  "strain_full" TEXT,
  "source" TEXT,
  "gene_type" TEXT,
  "sequence" TEXT,
  "band_size" TEXT,
  "url" TEXT,
  "notes" TEXT,
  "created_at" TEXT
);

CREATE TABLE IF NOT EXISTS "strains" (
  "id" INTEGER PRIMARY KEY,
  "name" TEXT NOT NULL UNIQUE,
  "notes" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

CREATE INDEX IF NOT EXISTS "ix_users_username" ON "users"("username");

CREATE INDEX IF NOT EXISTS "ix_claimers_name" ON "claimers"("name");

CREATE INDEX IF NOT EXISTS "ix_rooms_name" ON "rooms"("name");

CREATE INDEX IF NOT EXISTS "ix_cages_cage_code" ON "cages"("cage_code");

CREATE INDEX IF NOT EXISTS "ix_cages_room" ON "cages"("room");

CREATE INDEX IF NOT EXISTS "ix_mouse_statuses_name" ON "mouse_statuses"("name");

CREATE INDEX IF NOT EXISTS "ix_mice_mouse_code" ON "mice"("mouse_code");

CREATE INDEX IF NOT EXISTS "ix_mice_cage_id" ON "mice"("cage_id");

CREATE INDEX IF NOT EXISTS "ix_mice_strain" ON "mice"("strain");

CREATE INDEX IF NOT EXISTS "ix_mice_dob" ON "mice"("dob");

CREATE INDEX IF NOT EXISTS "ix_mice_owner_id" ON "mice"("owner_id");

CREATE INDEX IF NOT EXISTS "ix_mice_owner_name" ON "mice"("owner_name");

CREATE INDEX IF NOT EXISTS "ix_mice_status" ON "mice"("status");

CREATE INDEX IF NOT EXISTS "ix_mice_source_room" ON "mice"("source_room");

CREATE INDEX IF NOT EXISTS "ix_genotype_records_mouse_code" ON "genotype_records"("mouse_code");

CREATE INDEX IF NOT EXISTS "ix_genotype_records_mouse_id" ON "genotype_records"("mouse_id");

CREATE INDEX IF NOT EXISTS "ix_genotype_records_test_date" ON "genotype_records"("test_date");

CREATE INDEX IF NOT EXISTS "ix_genotype_records_strain" ON "genotype_records"("strain");

CREATE INDEX IF NOT EXISTS "ix_transfer_requests_seq" ON "transfer_requests"("seq");

CREATE INDEX IF NOT EXISTS "ix_transfer_requests_request_date" ON "transfer_requests"("request_date");

CREATE INDEX IF NOT EXISTS "ix_transfer_requests_demander" ON "transfer_requests"("demander");

CREATE INDEX IF NOT EXISTS "ix_transfer_requests_strain" ON "transfer_requests"("strain");

CREATE INDEX IF NOT EXISTS "ix_transfer_requests_target_room" ON "transfer_requests"("target_room");

CREATE INDEX IF NOT EXISTS "ix_transfer_requests_status" ON "transfer_requests"("status");

CREATE INDEX IF NOT EXISTS "ix_transfer_request_assignments_request_id" ON "transfer_request_assignments"("request_id");

CREATE INDEX IF NOT EXISTS "ix_transfer_logs_action_type" ON "transfer_logs"("action_type");

CREATE INDEX IF NOT EXISTS "ix_transfer_logs_claimer_name" ON "transfer_logs"("claimer_name");

CREATE INDEX IF NOT EXISTS "ix_transfer_logs_date" ON "transfer_logs"("date");

CREATE INDEX IF NOT EXISTS "ix_primers_strain_short" ON "primers"("strain_short");

CREATE INDEX IF NOT EXISTS "ix_strains_name" ON "strains"("name");

CREATE TABLE IF NOT EXISTS _revision (id INTEGER PRIMARY KEY CHECK(id=1), value INTEGER NOT NULL);

INSERT OR IGNORE INTO _revision VALUES(1, 0);

CREATE TABLE IF NOT EXISTS _write_guard (id INTEGER PRIMARY KEY CHECK(id=1));

CREATE TRIGGER IF NOT EXISTS "revision_users_insert" AFTER INSERT ON "users" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_users_update" AFTER UPDATE ON "users" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_users_delete" AFTER DELETE ON "users" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_claimers_insert" AFTER INSERT ON "claimers" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_claimers_update" AFTER UPDATE ON "claimers" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_claimers_delete" AFTER DELETE ON "claimers" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_rooms_insert" AFTER INSERT ON "rooms" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_rooms_update" AFTER UPDATE ON "rooms" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_rooms_delete" AFTER DELETE ON "rooms" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_cages_insert" AFTER INSERT ON "cages" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_cages_update" AFTER UPDATE ON "cages" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_cages_delete" AFTER DELETE ON "cages" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_mouse_statuses_insert" AFTER INSERT ON "mouse_statuses" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_mouse_statuses_update" AFTER UPDATE ON "mouse_statuses" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_mouse_statuses_delete" AFTER DELETE ON "mouse_statuses" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_mice_insert" AFTER INSERT ON "mice" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_mice_update" AFTER UPDATE ON "mice" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_mice_delete" AFTER DELETE ON "mice" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_genotype_records_insert" AFTER INSERT ON "genotype_records" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_genotype_records_update" AFTER UPDATE ON "genotype_records" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_genotype_records_delete" AFTER DELETE ON "genotype_records" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_transfer_requests_insert" AFTER INSERT ON "transfer_requests" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_transfer_requests_update" AFTER UPDATE ON "transfer_requests" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_transfer_requests_delete" AFTER DELETE ON "transfer_requests" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_transfer_request_assignments_insert" AFTER INSERT ON "transfer_request_assignments" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_transfer_request_assignments_update" AFTER UPDATE ON "transfer_request_assignments" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_transfer_request_assignments_delete" AFTER DELETE ON "transfer_request_assignments" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_transfer_logs_insert" AFTER INSERT ON "transfer_logs" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_transfer_logs_update" AFTER UPDATE ON "transfer_logs" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_transfer_logs_delete" AFTER DELETE ON "transfer_logs" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_primers_insert" AFTER INSERT ON "primers" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_primers_update" AFTER UPDATE ON "primers" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_primers_delete" AFTER DELETE ON "primers" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_strains_insert" AFTER INSERT ON "strains" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_strains_update" AFTER UPDATE ON "strains" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;

CREATE TRIGGER IF NOT EXISTS "revision_strains_delete" AFTER DELETE ON "strains" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;
