"""Generate the D1 schema and JS column/default metadata from the Python models.

Uses only the standard library; never opens or changes the laboratory database.
"""
import ast
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
tree = ast.parse((ROOT / 'backend/app/models/models.py').read_text(encoding='utf-8'))
tables = {}
ddl = []
indexes = []
for cls in tree.body:
    if not isinstance(cls, ast.ClassDef):
        continue
    assignments = {n.targets[0].id: n.value for n in cls.body if isinstance(n, ast.Assign) and isinstance(n.targets[0], ast.Name)}
    if '__tablename__' not in assignments:
        continue
    name = ast.literal_eval(assignments['__tablename__'])
    columns = {}
    sql_columns = []
    for field, call in assignments.items():
        if not isinstance(call, ast.Call) or not isinstance(call.func, ast.Name) or call.func.id != 'Column':
            continue
        options = {k.arg: k.value for k in call.keywords}
        kind = call.args[0]
        typename = kind.func.id if isinstance(kind, ast.Call) else kind.id
        default = None
        if 'default' in options:
            try:
                default = ast.literal_eval(options['default'])
            except ValueError:
                default = '$now'
        columns[field] = {'type': typename, 'default': default}
        sql = f'"{field}" ' + ('INTEGER' if typename in ('Integer', 'Boolean') else 'TEXT')
        if 'primary_key' in options:
            sql += ' PRIMARY KEY'
        if 'nullable' in options and not ast.literal_eval(options['nullable']):
            sql += ' NOT NULL'
        if 'unique' in options:
            sql += ' UNIQUE'
        for arg in call.args[1:]:
            if isinstance(arg, ast.Call) and isinstance(arg.func, ast.Name) and arg.func.id == 'ForeignKey':
                target, target_col = ast.literal_eval(arg.args[0]).split('.')
                ondelete = next((ast.literal_eval(k.value) for k in arg.keywords if k.arg == 'ondelete'), 'NO ACTION')
                sql += f' REFERENCES "{target}"("{target_col}") ON DELETE {ondelete}'
        sql_columns.append(sql)
        if 'index' in options and field != 'id':
            indexes.append(f'CREATE INDEX IF NOT EXISTS "ix_{name}_{field}" ON "{name}"("{field}");')
    tables[name] = columns
    ddl.append(f'CREATE TABLE IF NOT EXISTS "{name}" (\n  ' + ',\n  '.join(sql_columns) + '\n);')

ddl += indexes
business_sql = '\n\n'.join(ddl)
ddl += [
    'CREATE TABLE IF NOT EXISTS _revision (id INTEGER PRIMARY KEY CHECK(id=1), value INTEGER NOT NULL);',
    'INSERT OR IGNORE INTO _revision VALUES(1, 0);',
    'CREATE TABLE IF NOT EXISTS _write_guard (id INTEGER PRIMARY KEY CHECK(id=1));',
]
for name in tables:
    for action in ('INSERT', 'UPDATE', 'DELETE'):
        ddl.append(f'CREATE TRIGGER IF NOT EXISTS "revision_{name}_{action.lower()}" AFTER {action} ON "{name}" BEGIN UPDATE _revision SET value=value+1 WHERE id=1; END;')
target = ROOT / 'cloudflare/migrations/0001_initial.sql'
target.parent.mkdir(parents=True, exist_ok=True)
target.write_text('-- Generated by scripts/generate_cloudflare_schema.py\n' + '\n\n'.join(ddl) + '\n', encoding='utf-8')
(ROOT / 'cloudflare/schema.js').write_text('// Generated from backend/app/models/models.py.\nexport const schema = ' + json.dumps(tables, ensure_ascii=False, indent=2) + ';\nexport const createSql = ' + json.dumps(business_sql, ensure_ascii=False) + ';\n', encoding='utf-8')
strain_tree = ast.parse((ROOT / 'backend/app/services/strain_service.py').read_text(encoding='utf-8'))
mapping = next(ast.literal_eval(n.value) for n in strain_tree.body if isinstance(n, ast.Assign) and getattr(n.targets[0], 'id', '') == 'CANONICAL_STRAIN_MAP')
(ROOT / 'cloudflare/strain-map.js').write_text('export const strainMap = ' + json.dumps(mapping, ensure_ascii=False, indent=2) + ';\n', encoding='utf-8')
print(f'Generated {len(tables)} tables, {len(indexes)} indexes, and revision guards.')
